# Generated by Django 4.announcements.6 on 2023-02-10 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_profile_options_remove_profile_about_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='git_profile',
        ),
    ]
