# Generated by Django 4.1.6 on 2023-02-11 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_profile_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=models.CharField(default=996704289667, max_length=13, verbose_name='Номер'),
            preserve_default=False,
        ),
    ]
