# Generated by Django 4.announcements.6 on 2023-02-11 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='category_name',
            field=models.CharField(max_length=20, verbose_name='Category'),
        ),
    ]
