# Generated by Django 4.1.6 on 2023-02-11 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_alter_categories_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
