# Generated by Django 4.1.6 on 2023-02-11 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_remove_announcement_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='status',
            field=models.CharField(choices=[('moderate', 'модерация'), ('published', 'Опубликовано'), ('canceled', 'Отклонено'), ('deleted', 'Удаление')], default='moderate', max_length=15),
        ),
    ]
