# Generated by Django 4.1.6 on 2023-02-11 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_alter_announcement_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='announcement',
            options={'permissions': [('can_moderated', 'Может модерировать отзыв')]},
        ),
    ]
